name: BDD Test Runner (Simple)

on:
  workflow_dispatch:
    inputs:
      test_environment:
        description: 'Test environment'
        required: false
        default: 'staging'
        type: choice
        options:
        - staging
        - production
  push:
    branches: [ main, master ]
    paths:
    - 'test_cases/**'
    - '.github/workflows/test-runner-simple.yml'
  pull_request:
    branches: [ main, master ]
    paths:
    - 'test_cases/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Debug environment
      run: |
        echo "GitHub event: ${{ github.event_name }}"
        echo "Branch: ${{ github.ref }}"
        echo "Repository: ${{ github.repository }}"
        
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Verify Python installation
      run: |
        python --version
        which python
        python -c "import sys; print(f'Python {sys.version}')"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install behave pytest selenium requests beautifulsoup4
        
    - name: Install Playwright browsers
      run: |
        playwright install chromium
        playwright install-deps
        
    - name: Find and run test files
      run: |
        echo "Looking for test files..."
        if [ -d "test_cases" ]; then
          echo "test_cases directory found"
          find test_cases -name "*.feature" -o -name "*.yml" | head -10
          
          # Run behave on the test_cases directory
          echo "Running behave on test_cases directory"
          behave test_cases/ --format=json --outfile=test-results.json || echo "Test failed but continuing..."
        else
          echo "No test_cases directory found"
        fi
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results.json